manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: crazy-keyboards
      url-base: https://github.com/crazy-keyboards
    - name: englmaxi
      url-base: https://github.com/englmaxi
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-locales
      remote: crazy-keyboards
      revision: develop
    - name: zmk-dongle-display
      remote: englmaxi
      revision: main
  self:
    path: config