manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: crazy-keyboards
      url-base: https://github.com/crazy-keyboards
    - name: williambonfim
      url-base: https://github.com/williambonfim
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-locales
      remote: crazy-keyboards
      revision: develop
    - name: zmk-dongle-display
      remote: williambonfim
      revision: main
  self:
    path: config